repos:
- repo: https://github.com/pre-commit/mirrors-isort
  rev: v5.10.1
  hooks:
  - id: isort
- repo: https://github.com/ambv/black
  rev: 23.9.1
  hooks:
  - id: black
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
  - id: check-case-conflict
  - id: end-of-file-fixer
  - id: mixed-line-ending
    args:
    - --fix=lf
  - id: trailing-whitespace
  - id: pretty-format-json
    args:
    - --autofix
    - --indent=4
    - --no-sort-keys
  - id: check-merge-conflict
  - id: check-yaml
- repo: https://github.com/pycqa/flake8
  rev: 6.1.0
  hooks:
  - id: flake8
    additional_dependencies:
    - flake8-bugbear>=19.3.0
    - flake8-builtins>=1.4.1
    - flake8-commas>=2.0.0
    - flake8-comprehensions>=2.1.0
    - flake8-debugger>=3.1.0
    - flake8-pep3101>=1.2.1
- repo: https://github.com/pre-commit/pygrep-hooks
  rev: v1.10.0
  hooks:
  - id: python-check-blanket-noqa
  - id: python-check-mock-methods
  - id: python-no-log-warn
- repo: https://github.com/PyCQA/bandit
  rev: 1.7.5  # TODO: update once a release > 1.5.1 hits with this change in
  hooks:
  - id: bandit
    files: "^python/"
- repo: local
  hooks:
  - id: pylint-local
    name: pylint-local
    description: Run pylint in the local virtualenv
    entry: pylint "setup.py" "python/" "tests/"
    language: system
    # ignore all files, run on hard-coded modules instead
    pass_filenames: false
    always_run: true
  - id: pytest-local
    name: pytest-local
    description: Run pytest in the local virtualenv
    entry: pytest --cov-report term-missing --cov=rpdk.java --doctest-modules tests/
    language: system
    # ignore all files, run on hard-coded modules instead
    pass_filenames: false
    always_run: true
