version: 0.2
phases:
  install:
    commands:
      # make sure pip/setuptools/wheel is up to date, awscli for SDK patching
      - pip install --upgrade pip setuptools wheel awscli -r requirements.txt
      - aws configure add-model --service-model "file://$CODEBUILD_SRC_DIR_RPDK/cloudformation-2010-05-15.normal.json" --service-name cloudformation
      # setup git-secrets
      - WD=$(pwd)
      - cd /tmp
      - git clone https://github.com/awslabs/git-secrets.git
      - cd git-secrets
      - make install
      - cd ${WD}
  build:
    commands:
      # install internal SDK
      - >
        mvn org.apache.maven.plugins:maven-install-plugin:3.0.0-M1:install-file --batch-mode
        -Dfile="$CODEBUILD_SRC_DIR_SDK/cloudformation-2.5.69.jar"
      # install aws-cloudformation-resource-schema
      - cd "$CODEBUILD_SRC_DIR_SCHEMA"
      - mvn package org.apache.maven.plugins:maven-install-plugin:3.0.0-M1:install --batch-mode
      # install aws-cloudformation-rpdk-java-plugin and rpdk core
      - cd "$CODEBUILD_SRC_DIR"
      - mvn package org.apache.maven.plugins:maven-install-plugin:3.0.0-M1:install --batch-mode
      - pip install "$CODEBUILD_SRC_DIR_RPDK" .
      - pre-commit run --all-files
      # ensure code was linted
      - mvn com.diffplug.spotless:spotless-maven-plugin:check
      # end-to-end test
      - DIR=$(mktemp -d)
      - cd "$DIR"
      - ls -la
      - printf "AWS::Foo::Bar\n\n" | cfn-cli init -vv
      - mvn clean verify
      - ls -la
