version: 0.2
phases:
  install:
    runtime-versions:
      java: openjdk8
      python: 3.7
    commands:
      # make sure pip/setuptools/wheel is up to date, awscli for SDK patching
      - cd "$CODEBUILD_SRC_DIR_RPDK"
      - pip install --upgrade pip setuptools wheel awscli -r "requirements.txt"
      # setup git-secrets
      - WD=$(pwd)
      - cd /tmp
      - git clone https://github.com/awslabs/git-secrets.git
      - cd git-secrets
      - make install
      - cd "$WD"
  build:
    commands:
      # install aws-cloudformation-rpdk-java-plugin and rpdk core
      - cd "$CODEBUILD_SRC_DIR"
      - >
        mvn package org.apache.maven.plugins:maven-install-plugin:3.0.0-M1:install
        --batch-mode
        --no-transfer-progress
      - pip install "$CODEBUILD_SRC_DIR_RPDK" .
      - pre-commit run --all-files
      # end-to-end test
      - DIR=$(mktemp -d)
      - cd "$DIR"
      - ls -la
      - printf "AWS::Foo::Bar\n\n" | cfn init -vv
      - mvn clean verify
      - ls -la
